import Head from 'next/head'
import { listCollectionsService } from '@services/collection/listCollectionsService';
import { CollectionItemsList } from '@components/collection/CollectionItemsList';
import About from '@components/About';

export default function Home({ collections }) {
    return (
        <div>
            <Head>
                <title>Collectiion Manager</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col gap-20">                
                { collections.length > 0 ? <CollectionItemsList collections={collections} /> : null }
                <About />
            </div>
        </div>
    )
}

export async function getStaticProps() {
    const { data:collections } = await listCollectionsService({});
    return {
        props: {
            collections: collections.data,
        }
    };
}
